# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'qt6_main_window.ui'
##
## Created by: Qt User Interface Compiler version 6.5.1
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QCheckBox, QComboBox, QFrame,
    QHeaderView, QLabel, QLineEdit, QMainWindow,
    QPushButton, QScrollArea, QSizePolicy, QStatusBar,
    QTabWidget, QTableWidget, QTableWidgetItem, QVBoxLayout,
    QWidget)
import gui_app.main_imag_window

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(1024, 768)
        MainWindow.setMinimumSize(QSize(1024, 768))
        MainWindow.setMaximumSize(QSize(1024, 768))
        MainWindow.setToolButtonStyle(Qt.ToolButtonTextBesideIcon)
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.verticalLayout = QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName(u"verticalLayout")
        self.frame_tab_widget = QTabWidget(self.centralwidget)
        self.frame_tab_widget.setObjectName(u"frame_tab_widget")
        self.frame_tab_widget.setFocusPolicy(Qt.NoFocus)
        self.frame_tab_widget.setTabPosition(QTabWidget.West)
        self.frame_tab_widget.setTabShape(QTabWidget.Rounded)
        self.f_news = QWidget()
        self.f_news.setObjectName(u"f_news")
        sizePolicy = QSizePolicy(QSizePolicy.Preferred, QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.f_news.sizePolicy().hasHeightForWidth())
        self.f_news.setSizePolicy(sizePolicy)
        self.f_news.setSizeIncrement(QSize(0, 0))
        self.f_news.setBaseSize(QSize(0, 0))
        self.f_btc = QFrame(self.f_news)
        self.f_btc.setObjectName(u"f_btc")
        self.f_btc.setGeometry(QRect(700, 10, 271, 71))
        self.f_btc.setFrameShape(QFrame.Box)
        self.f_btc.setFrameShadow(QFrame.Raised)
        self.label = QLabel(self.f_btc)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(10, 10, 191, 51))
        self.label.setFrameShape(QFrame.Box)
        self.label_2 = QLabel(self.f_btc)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(210, 10, 51, 51))
        self.label_2.setFrameShape(QFrame.Box)
        self.f_cript = QFrame(self.f_news)
        self.f_cript.setObjectName(u"f_cript")
        self.f_cript.setGeometry(QRect(700, 90, 271, 621))
        self.f_cript.setFrameShape(QFrame.Box)
        self.f_cript.setFrameShadow(QFrame.Raised)
        self.scrollArea = QScrollArea(self.f_news)
        self.scrollArea.setObjectName(u"scrollArea")
        self.scrollArea.setGeometry(QRect(9, 9, 681, 701))
        self.scrollArea.setWidgetResizable(True)
        self.scrollAreaWidgetContents = QWidget()
        self.scrollAreaWidgetContents.setObjectName(u"scrollAreaWidgetContents")
        self.scrollAreaWidgetContents.setGeometry(QRect(0, 0, 679, 699))
        self.label_3 = QLabel(self.scrollAreaWidgetContents)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(0, 0, 681, 701))
        self.label_3.setFrameShape(QFrame.NoFrame)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.frame_tab_widget.addTab(self.f_news, "")
        self.f_wall = QWidget()
        self.f_wall.setObjectName(u"f_wall")
        self.tableWidget = QTableWidget(self.f_wall)
        self.tableWidget.setObjectName(u"tableWidget")
        self.tableWidget.setGeometry(QRect(10, 10, 961, 641))
        self.btn_new = QPushButton(self.f_wall)
        self.btn_new.setObjectName(u"btn_new")
        self.btn_new.setGeometry(QRect(60, 670, 151, 41))
        icon = QIcon()
        icon.addFile(u":/icon/images/add_user_dark.png", QSize(), QIcon.Normal, QIcon.Off)
        self.btn_new.setIcon(icon)
        self.btn_edited = QPushButton(self.f_wall)
        self.btn_edited.setObjectName(u"btn_edited")
        self.btn_edited.setGeometry(QRect(410, 670, 151, 41))
        self.btn_deleted = QPushButton(self.f_wall)
        self.btn_deleted.setObjectName(u"btn_deleted")
        self.btn_deleted.setGeometry(QRect(760, 670, 151, 41))
        self.frame_tab_widget.addTab(self.f_wall, "")
        self.f_setti = QWidget()
        self.f_setti.setObjectName(u"f_setti")
        self.btn_save = QPushButton(self.f_setti)
        self.btn_save.setObjectName(u"btn_save")
        self.btn_save.setGeometry(QRect(790, 500, 161, 71))
        self.btn_backup = QPushButton(self.f_setti)
        self.btn_backup.setObjectName(u"btn_backup")
        self.btn_backup.setGeometry(QRect(560, 500, 161, 71))
        self.by_label = QLabel(self.f_setti)
        self.by_label.setObjectName(u"by_label")
        self.by_label.setGeometry(QRect(20, 400, 461, 301))
        self.by_label.setFrameShape(QFrame.Box)
        self.by_label.setFrameShadow(QFrame.Plain)
        self.by_label.setLineWidth(1)
        self.by_label.setMidLineWidth(0)
        self.comboBox = QComboBox(self.f_setti)
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.setObjectName(u"comboBox")
        self.comboBox.setGeometry(QRect(80, 80, 201, 41))
        font = QFont()
        font.setPointSize(16)
        font.setBold(True)
        self.comboBox.setFont(font)
        self.comboBox.setFocusPolicy(Qt.ClickFocus)
        self.comboBox.setInsertPolicy(QComboBox.InsertAtBottom)
        self.f_proxy_sett = QFrame(self.f_setti)
        self.f_proxy_sett.setObjectName(u"f_proxy_sett")
        self.f_proxy_sett.setGeometry(QRect(360, 80, 591, 191))
        self.f_proxy_sett.setFrameShape(QFrame.StyledPanel)
        self.f_proxy_sett.setFrameShadow(QFrame.Raised)
        self.lineEdit = QLineEdit(self.f_proxy_sett)
        self.lineEdit.setObjectName(u"lineEdit")
        self.lineEdit.setGeometry(QRect(150, 80, 261, 41))
        self.lineEdit.setMaxLength(64)
        self.lineEdit_2 = QLineEdit(self.f_proxy_sett)
        self.lineEdit_2.setObjectName(u"lineEdit_2")
        self.lineEdit_2.setGeometry(QRect(430, 80, 121, 41))
        font1 = QFont()
        font1.setPointSize(14)
        font1.setBold(True)
        self.lineEdit_2.setFont(font1)
        self.lineEdit_2.setInputMask(u"")
        self.lineEdit_2.setMaxLength(5)
        self.cb_proxy = QCheckBox(self.f_proxy_sett)
        self.cb_proxy.setObjectName(u"cb_proxy")
        self.cb_proxy.setGeometry(QRect(50, 80, 90, 41))
        sizePolicy1 = QSizePolicy(QSizePolicy.Minimum, QSizePolicy.Fixed)
        sizePolicy1.setHorizontalStretch(0)
        sizePolicy1.setVerticalStretch(0)
        sizePolicy1.setHeightForWidth(self.cb_proxy.sizePolicy().hasHeightForWidth())
        self.cb_proxy.setSizePolicy(sizePolicy1)
        self.cb_proxy.setMaximumSize(QSize(90, 41))
        self.cb_proxy.setSizeIncrement(QSize(0, 0))
        self.cb_proxy.setBaseSize(QSize(0, 0))
        font2 = QFont()
        font2.setPointSize(11)
        font2.setBold(False)
        self.cb_proxy.setFont(font2)
        self.cb_proxy.setIconSize(QSize(16, 16))
        self.ps_label = QLabel(self.f_proxy_sett)
        self.ps_label.setObjectName(u"ps_label")
        self.ps_label.setGeometry(QRect(10, 10, 571, 51))
        self.ps_label.setFont(font1)
        self.ps_label.setTextFormat(Qt.PlainText)
        self.ps_label.setAlignment(Qt.AlignCenter)
        self.frame_tab_widget.addTab(self.f_setti, "")

        self.verticalLayout.addWidget(self.frame_tab_widget)

        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)

        self.frame_tab_widget.setCurrentIndex(0)


        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"Crypto Wallet List", None))
        self.label.setText(QCoreApplication.translate("MainWindow", u"TextLabel", None))
        self.label_2.setText(QCoreApplication.translate("MainWindow", u"TextLabel", None))
        self.label_3.setText(QCoreApplication.translate("MainWindow", u"TextLabel", None))
        self.frame_tab_widget.setTabText(self.frame_tab_widget.indexOf(self.f_news), QCoreApplication.translate("MainWindow", u"News", None))
        self.btn_new.setText(QCoreApplication.translate("MainWindow", u"New", None))
        self.btn_edited.setText(QCoreApplication.translate("MainWindow", u"Edited", None))
        self.btn_deleted.setText(QCoreApplication.translate("MainWindow", u"Delete", None))
        self.frame_tab_widget.setTabText(self.frame_tab_widget.indexOf(self.f_wall), QCoreApplication.translate("MainWindow", u"Wallet", None))
        self.btn_save.setText(QCoreApplication.translate("MainWindow", u"Save", None))
        self.btn_backup.setText(QCoreApplication.translate("MainWindow", u"Backup", None))
        self.by_label.setText(QCoreApplication.translate("MainWindow", u"@ By", None))
        self.comboBox.setItemText(0, QCoreApplication.translate("MainWindow", u"English", None))
        self.comboBox.setItemText(1, QCoreApplication.translate("MainWindow", u"Ukrainian", None))

        self.comboBox.setCurrentText(QCoreApplication.translate("MainWindow", u"English", None))
        self.lineEdit_2.setText("")
        self.cb_proxy.setText(QCoreApplication.translate("MainWindow", u"On Proxy", None))
        self.ps_label.setText(QCoreApplication.translate("MainWindow", u"Proxy Settings", None))
        self.frame_tab_widget.setTabText(self.frame_tab_widget.indexOf(self.f_setti), QCoreApplication.translate("MainWindow", u"Settings", None))
    # retranslateUi

